### ISSUE TITLE
hitcount_cleanup does not work in 1.8

### ISSUE THREAD

**Issue by thornomad** [thornomad/django-hitcount#34]
1.8 changed something with the transactions:

    Traceback (most recent call last):
      File "../../django-hitcount/hitcount/management/commands/hitcount_cleanup.py", line 21, in handle_noargs
        transaction.commit_unless_managed()
    AttributeError: 'module' object has no attribute 'commit_unless_managed'

Need to fix that -- broken for now.
